# Data Preprocessing

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# 1. Data Loading

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/IPL_Data_Analysis/att_0_1778303821_c3a907.csv")
df.head()

/tmp/ipykernel_1291/4067506012.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/drive/MyDrive/IPL_Data_Analysis/att_0_1778303821_c3a907.csv")

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,...,non_striker,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out
0,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,0,0,0,0,0,0,0,NaN,NaN
1,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,0,0,0,0,0,0,0,NaN,NaN
2,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,4,0,4,0,0,0,0,NaN,NaN
3,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,0,0,0,0,0,0,0,NaN,NaN
4,1082591,2017-04-05,2017,Indian Premier League,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,...,S Dhawan,0,2,2,2,0,0,0,NaN,NaN

# 2. Data Understanding

### Data Size - Rows and Columns

In [ ]:
df.shape

(289673, 30)

### Data Types

In [ ]:
df.dtypes

match_id               int64
date                  object
season                object
event                 object
venue                 object
city                  object
team1                 object
team2                 object
toss_winner           object
toss_decision         object
winner                object
win_by_runs          float64
win_by_wickets       float64
player_of_match       object
innings                int64
batting_team          object
over                   int64
ball                   int64
batter                object
bowler                object
non_striker           object
runs_batter            int64
runs_extras            int64
runs_total             int64
extras_wides           int64
extras_noballs         int64
extras_byes            int64
extras_legbyes         int64
wicket_kind           object
wicket_player_out     object
dtype: object

### Unique Values in Some Columns

In [ ]:
for column in df.columns:
    if df[column].dtype == 'object':
        print(f"Unique values in column '{column}':\n{df[column].unique()}\n")

Unique values in column 'date':
['2017-04-05' '2017-04-06' '2017-04-07' '2017-04-08' '2017-04-09'
 '2017-04-10' '2017-04-11' '2017-04-12' '2017-04-13' '2017-04-14'
 '2017-04-15' '2017-04-16' '2017-04-17' '2017-04-18' '2017-04-19'
 '2017-04-20' '2017-04-21' '2017-04-22' '2017-04-23' '2017-04-24'
 '2017-04-26' '2017-04-27' '2017-04-28' '2017-04-29' '2017-04-30'
 '2017-05-01' '2017-05-02' '2017-05-03' '2017-05-04' '2017-05-05'
 '2017-05-06' '2017-05-07' '2017-05-08' '2017-05-09' '2017-05-10'
 '2017-05-11' '2017-05-12' '2017-05-13' '2017-05-14' '2017-05-16'
 '2017-05-17' '2017-05-19' '2017-05-21' '2018-04-07' '2018-04-08'
 '2018-04-09' '2018-04-10' '2018-04-11' '2018-04-12' '2018-04-13'
 '2018-04-14' '2018-04-15' '2018-04-16' '2018-04-17' '2018-04-18'
 '2018-04-19' '2018-04-20' '2018-04-21' '2018-04-22' '2018-04-23'
 '2018-04-24' '2018-04-25' '2018-04-26' '2018-04-27' '2018-04-28'
 '2018-04-29' '2018-04-30' '2018-05-01' '2018-05-02' '2018-05-03'
 '2018-05-04' '2018-05-05' '2018-05-06' '2018-05-07' '2018-05-08'
 '2018-05-09' '2018-05-10' '2018-05-11' '2018-05-12' '2018-05-13'
 '2018-05-14' '2018-05-15' '2018-05-16' '2018-05-17' '2018-05-18'
 '2018-05-19' '2018-05-20' '2018-05-22' '2018-05-23' '2018-05-25'
 '2018-05-27' '2019-03-23' '2019-03-24' '2019-03-25' '2019-03-26'
 '2019-03-27' '2019-03-28' '2019-03-29' '2019-03-30' '2019-03-31'
 '2019-04-01' '2019-04-02' '2019-04-03' '2019-04-04' '2019-04-05'
 '2019-04-06' '2019-04-07' '2019-04-08' '2019-04-09' '2019-04-10'
 '2019-04-11' '2019-04-12' '2019-04-13' '2019-04-14' '2019-04-15'
 '2019-04-16' '2019-04-17' '2019-04-18' '2019-04-19' '2019-04-20'
 '2019-04-21' '2019-04-22' '2019-04-23' '2019-04-24' '2019-04-25'
 '2019-04-26' '2019-04-27' '2019-04-28' '2019-04-29' '2019-04-30'
 '2019-05-01' '2019-05-02' '2019-05-03' '2019-05-04' '2019-05-05'
 '2019-05-07' '2019-05-08' '2019-05-10' '2019-05-12' '2020-09-19'
 '2020-09-20' '2020-10-21' '2020-11-03' '2020-09-22' '2020-10-24'
 '2020-10-28' '2020-10-09' '2020-10-07' '2020-10-31' '2020-10-01'
 '2020-09-30' '2020-11-02' '2020-11-01' '2020-10-11' '2020-09-23'
 '2020-10-17' '2020-09-24' '2020-10-06' '2020-10-18' '2020-10-04'
 '2020-10-03' '2020-10-02' '2020-10-22' '2020-10-05' '2020-10-26'
 '2020-10-23' '2020-10-10' '2020-10-27' '2020-10-16' '2020-09-27'
 '2020-10-13' '2020-10-15' '2020-09-29' '2020-10-19' '2020-09-21'
 '2020-10-29' '2020-10-30' '2020-09-25' '2020-10-12' '2020-10-25'
 '2020-10-08' '2020-10-14' '2020-09-26' '2020-10-20' '2020-09-28'
 '2020-11-05' '2020-11-06' '2020-11-08' '2020-11-10' '2021-04-09'
 '2021-04-10' '2021-04-11' '2021-04-12' '2021-04-13' '2021-04-14'
 '2021-04-15' '2021-04-16' '2021-04-17' '2021-04-18' '2021-04-19'
 '2021-04-20' '2021-04-21' '2021-04-22' '2021-04-23' '2021-04-24'
 '2021-04-25' '2021-04-26' '2021-04-27' '2021-04-28' '2021-04-29'
 '2021-04-30' '2021-05-01' '2021-05-02' '2021-09-20' '2021-10-08'
 '2021-10-02' '2021-10-03' '2021-09-30' '2021-09-28' '2021-10-05'
 '2021-10-07' '2021-10-06' '2021-09-23' '2021-09-25' '2021-09-26'
 '2021-09-27' '2021-10-01' '2021-09-29' '2021-09-19' '2021-09-22'
 '2021-10-04' '2021-09-21' '2021-09-24' '2021-10-10' '2021-10-11'
 '2021-10-13' '2021-10-15' '2022-03-26' '2022-03-27' '2022-03-28'
 '2022-03-29' '2022-03-30' '2022-03-31' '2022-04-01' '2022-04-02'
 '2022-04-03' '2022-04-04' '2022-04-05' '2022-04-06' '2022-04-07'
 '2022-04-08' '2022-04-09' '2022-04-10' '2022-04-11' '2022-04-12'
 '2022-04-13' '2022-04-14' '2022-04-15' '2022-04-16' '2022-04-17'
 '2022-04-18' '2022-04-19' '2022-04-20' '2022-04-21' '2022-04-22'
 '2022-04-23' '2022-04-24' '2022-04-25' '2022-04-26' '2022-04-27'
 '2022-04-28' '2022-04-29' '2022-04-30' '2022-05-01' '2022-05-02'
 '2022-05-03' '2022-05-04' '2022-05-05' '2022-05-06' '2022-05-07'
 '2022-05-08' '2022-05-09' '2022-05-10' '2022-05-11' '2022-05-12'
 '2022-05-13' '2022-05-14' '2022-05-15' '2022-05-16' '2022-05-17'
 '2022-05-18' '2022-05-19' '2022-05-20' '2022-05-21' '2022-05-22'
 '2022-05-24' '2022-05-25' '2022-05-27' '2022-05-29' '2023-03-31'
 '2023-04-01' '2023-04-02' '2023-04-03' '2023-04-04' '2023-04-05'
 '2023-04-06' '2023-04-07' '2023-04-08' '2023-04-09' '2023-04-10'
 '2023-04-11' '2023-04-12' '2023-04-13' '2023-04-14' '2023-04-15'
 '2023-04-16' '2023-04-17' '2023-04-18' '2023-04-19' '2023-04-20'
 '2023-04-21' '2023-04-22' '2023-04-23' '2023-04-24' '2023-04-25'
 '2023-04-26' '2023-04-27' '2023-04-28' '2023-04-29' '2023-04-30'
 '2023-05-01' '2023-05-02' '2023-05-03' '2023-05-04' '2023-05-05'
 '2023-05-06' '2023-05-07' '2023-05-08' '2023-05-09' '2023-05-10'
 '2023-05-11' '2023-05-12' '2023-05-13' '2023-05-14' '2023-05-15'
 '2023-05-16' '2023-05-17' '2023-05-18' '2023-05-19' '2023-05-20'
 '2023-05-21' '2023-05-23' '2023-05-24' '2023-05-26' '2023-05-29'
 '2024-03-22' '2024-03-23' '2024-03-24' '2024-03-25' '2024-03-26'
 '2024-03-27' '2024-03-28' '2024-03-29' '2024-03-30' '2024-03-31'
 '2024-04-01' '2024-04-02' '2024-04-03' '2024-04-04' '2024-04-05'
 '2024-04-06' '2024-04-07' '2024-04-08' '2024-04-09' '2024-04-10'
 '2024-04-11' '2024-04-12' '2024-04-13' '2024-04-14' '2024-04-15'
 '2024-04-16' '2024-04-17' '2024-04-18' '2024-04-19' '2024-04-20'
 '2024-04-21' '2024-04-22' '2024-04-23' '2024-04-24' '2024-04-25'
 '2024-04-26' '2024-04-27' '2024-04-28' '2024-04-29' '2024-04-30'
 '2024-05-01' '2024-05-02' '2024-05-03' '2024-05-04' '2024-05-05'
 '2024-05-06' '2024-05-07' '2024-05-08' '2024-05-09' '2024-05-10'
 '2024-05-11' '2024-05-12' '2024-05-14' '2024-05-15' '2024-05-17'
 '2024-05-18' '2024-05-19' '2024-05-21' '2024-05-22' '2024-05-24'
 '2024-05-26' '2025-03-22' '2025-03-23' '2025-03-24' '2025-03-25'
 '2025-03-26' '2025-03-27' '2025-03-28' '2025-03-29' '2025-03-30'
 '2025-03-31' '2025-04-01' '2025-04-02' '2025-04-03' '2025-04-04'
 '2025-04-05' '2025-04-08' '2025-04-06' '2025-04-07' '2025-04-09'
 '2025-04-10' '2025-04-11' '2025-04-12' '2025-04-13' '2025-04-14'
 '2025-04-15' '2025-04-16' '2025-04-17' '2025-04-18' '2025-04-19'
 '2025-04-20' '2025-04-21' '2025-04-22' '2025-04-23' '2025-04-24'
 '2025-04-25' '2025-04-26' '2025-04-27' '2025-04-28' '2025-04-29'
 '2025-04-30' '2025-05-01' '2025-05-02' '2025-05-03' '2025-05-04'
 '2025-05-05' '2025-05-06' '2025-05-07' '2025-05-08' '2025-05-18'
 '2025-05-19' '2025-05-20' '2025-05-21' '2025-05-22' '2025-05-23'
 '2025-05-25' '2025-05-26' '2025-05-27' '2025-05-29' '2025-05-30'
 '2025-06-01' '2025-06-03' '2025-05-24' '2008-04-18' '2008-04-19'
 '2008-04-20' '2008-04-21' '2008-04-22' '2008-04-23' '2008-04-24'
 '2008-04-25' '2008-04-26' '2008-04-27' '2008-04-28' '2008-04-29'
 '2008-04-30' '2008-05-01' '2008-05-02' '2008-05-25' '2008-05-03'
 '2008-05-04' '2008-05-05' '2008-05-06' '2008-05-07' '2008-05-08'
 '2008-05-09' '2008-05-28' '2008-05-10' '2008-05-11' '2008-05-12'
 '2008-05-13' '2008-05-14' '2008-05-15' '2008-05-16' '2008-05-17'
 '2008-05-18' '2008-05-19' '2008-05-20' '2008-05-21' '2008-05-23'
 '2008-05-24' '2008-05-26' '2008-05-27' '2008-05-30' '2008-05-31'
 '2008-06-01' '2009-04-18' '2009-04-19' '2009-04-20' '2009-04-21'
 '2009-04-22' '2009-04-23' '2009-04-24' '2009-04-25' '2009-04-26'
 '2009-04-27' '2009-04-28' '2009-04-29' '2009-04-30' '2009-05-01'
 '2009-05-02' '2009-05-03' '2009-05-04' '2009-05-05' '2009-05-06'
 '2009-05-07' '2009-05-08' '2009-05-09' '2009-05-10' '2009-05-11'
 '2009-05-12' '2009-05-13' '2009-05-14' '2009-05-15' '2009-05-16'
 '2009-05-17' '2009-05-18' '2009-05-19' '2009-05-20' '2009-05-21'
 '2009-05-22' '2009-05-23' '2009-05-24' '2010-03-12' '2010-03-13'
 '2010-03-14' '2010-03-15' '2010-03-16' '2010-03-17' '2010-03-18'
 '2010-03-19' '2010-03-20' '2010-03-21' '2010-03-22' '2010-03-23'
 '2010-03-24' '2010-03-25' '2010-03-26' '2010-03-27' '2010-03-28'
 '2010-03-29' '2010-03-30' '2010-03-31' '2010-04-01' '2010-04-02'
 '2010-04-03' '2010-04-04' '2010-04-05' '2010-04-06' '2010-04-07'
 '2010-04-08' '2010-04-09' '2010-04-10' '2010-04-11' '2010-04-12'
 '2010-04-13' '2010-04-14' '2010-04-15' '2010-04-16' '2010-04-17'
 '2010-04-18' '2010-04-19' '2010-04-21' '2010-04-22' '2010-04-24'
 '2010-04-25' '2011-04-08' '2011-04-09' '2011-04-10' '2011-04-11'
 '2011-04-12' '2011-04-13' '2011-04-14' '2011-04-15' '2011-04-16'
 '2011-04-17' '2011-04-18' '2011-04-19' '2011-04-20' '2011-04-21'
 '2011-04-22' '2011-04-23' '2011-04-24' '2011-04-25' '2011-04-26'
 '2011-04-27' '2011-04-28' '2011-04-29' '2011-04-30' '2011-05-01'
 '2011-05-02' '2011-05-03' '2011-05-04' '2011-05-05' '2011-05-06'
 '2011-05-07' '2011-05-08' '2011-05-09' '2011-05-10' '2011-05-11'
 '2011-05-12' '2011-05-13' '2011-05-14' '2011-05-15' '2011-05-16'
 '2011-05-17' '2011-05-18' '2011-05-19' '2011-05-20' '2011-05-21'
 '2011-05-22' '2011-05-24' '2011-05-25' '2011-05-27' '2011-05-28'
 '2012-04-04' '2012-04-05' '2012-04-06' '2012-04-07' '2012-04-08'
 '2012-04-09' '2012-04-10' '2012-04-11' '2012-04-12' '2012-04-13'
 '2012-04-19' '2012-04-14' '2012-04-15' '2012-04-16' '2012-04-17'
 '2012-04-18' '2012-05-10' '2012-04-20' '2012-04-21' '2012-04-22'
 '2012-04-23' '2012-04-24' '2012-04-25' '2012-04-26' '2012-04-27'
 '2012-04-28' '2012-04-29' '2012-04-30' '2012-05-01' '2012-05-02'
 '2012-05-03' '2012-05-04' '2012-05-05' '2012-05-06' '2012-05-07'
 '2012-05-08' '2012-05-09' '2012-05-11' '2012-05-12' '2012-05-13'
 '2012-05-14' '2012-05-15' '2012-05-16' '2012-05-17' '2012-05-18'
 '2012-05-19' '2012-05-20' '2012-05-22' '2012-05-23' '2012-05-25'
 '2012-05-27' '2013-04-03' '2013-04-04' '2013-04-05' '2013-04-06'
 '2013-04-07' '2013-04-08' '2013-04-09' '2013-04-10' '2013-04-11'
 '2013-04-12' '2013-04-13' '2013-04-14' '2013-04-15' '2013-04-16'
 '2013-04-17' '2013-04-18' '2013-04-19' '2013-04-20' '2013-04-21'
 '2013-04-22' '2013-04-23' '2013-05-16' '2013-04-24' '2013-04-25'
 '2013-04-26' '2013-04-27' '2013-04-28' '2013-04-29' '2013-04-30'
 '2013-05-01' '2013-05-02' '2013-05-03' '2013-05-04' '2013-05-14'
 '2013-05-05' '2013-05-07' '2013-05-08' '2013-05-09' '2013-05-10'
 '2013-05-11' '2013-05-12' '2013-05-13' '2013-05-15' '2013-05-06'
 '2013-05-17' '2013-05-18' '2013-05-19' '2013-05-21' '2013-05-22'
 '2013-05-24' '2013-05-26' '2014-04-16' '2014-04-17' '2014-04-18'
 '2014-04-19' '2014-04-20' '2014-04-21' '2014-04-22' '2014-04-23'
 '2014-04-24' '2014-04-25' '2014-04-26' '2014-04-27' '2014-04-28'
 '2014-04-29' '2014-04-30' '2014-05-02' '2014-05-03' '2014-05-04'
 '2014-05-05' '2014-05-06' '2014-05-07' '2014-05-08' '2014-05-09'
 '2014-05-10' '2014-05-11' '2014-05-12' '2014-05-13' '2014-05-14'
 '2014-05-15' '2014-05-18' '2014-05-19' '2014-05-20' '2014-05-21'
 '2014-05-22' '2014-05-23' '2014-05-24' '2014-05-25' '2014-05-27'
 '2014-05-28' '2014-05-30' '2014-06-01' '2015-04-08' '2015-04-09'
 '2015-04-10' '2015-04-11' '2015-04-12' '2015-04-13' '2015-04-14'
 '2015-04-30' '2015-04-15' '2015-04-16' '2015-04-17' '2015-04-18'
 '2015-04-19' '2015-04-20' '2015-04-21' '2015-04-22' '2015-04-23'
 '2015-04-24' '2015-04-25' '2015-04-26' '2015-04-27' '2015-05-07'
 '2015-04-29' '2015-04-28' '2015-05-01' '2015-05-02' '2015-05-03'
 '2015-05-04' '2015-05-05' '2015-05-06' '2015-05-08' '2015-05-09'
 '2015-05-10' '2015-05-11' '2015-05-12' '2015-05-13' '2015-05-14'
 '2015-05-15' '2015-05-16' '2015-05-17' '2015-05-19' '2015-05-20'
 '2015-05-22' '2015-05-24' '2016-04-09' '2016-04-10' '2016-04-11'
 '2016-04-12' '2016-04-13' '2016-04-14' '2016-04-15' '2016-04-16'
 '2016-04-17' '2016-04-18' '2016-04-19' '2016-04-20' '2016-04-21'
 '2016-04-22' '2016-04-23' '2016-04-24' '2016-04-25' '2016-04-26'
 '2016-04-27' '2016-04-28' '2016-04-29' '2016-04-30' '2016-05-01'
 '2016-05-02' '2016-05-03' '2016-05-04' '2016-05-05' '2016-05-06'
 '2016-05-07' '2016-05-08' '2016-05-09' '2016-05-10' '2016-05-11'
 '2016-05-12' '2016-05-13' '2016-05-14' '2016-05-15' '2016-05-16'
 '2016-05-17' '2016-05-18' '2016-05-19' '2016-05-20' '2016-05-21'
 '2016-05-22' '2016-05-24' '2016-05-25' '2016-05-27' '2016-05-29'
 '2026-03-28' '2026-03-29' '2026-03-30' '2026-03-31' '2026-04-01'
 '2026-04-02' '2026-04-03' '2026-04-04' '2026-04-05' '2026-04-06'
 '2026-04-07' '2026-04-08' '2026-04-09' '2026-04-10' '2026-04-11'
 '2026-04-12' '2026-04-13' '2026-04-14' '2026-04-15' '2026-04-16'
 '2026-04-17' '2026-04-18' '2026-04-19' '2026-04-20' '2026-04-21'
 '2026-04-22' '2026-04-23' '2026-04-24' '2026-04-25' '2026-04-26'
 '2026-04-27' '2026-04-28' '2026-04-29' '2026-04-30' '2026-05-01'
 '2026-05-02' '2026-05-03' '2026-05-04' '2026-05-05' '2026-05-06']

Unique values in column 'season':
[2017 2018 2019 '2019' '2020/21' '2021' 2021 2022 2023 2024 2025 '2025'
 '2007/08' '2009' '2009/10' '2011' 2011 2012 2013 2014 2015 2016 2026]

Unique values in column 'event':
['Indian Premier League']

Unique values in column 'venue':
['Rajiv Gandhi International Stadium, Uppal'
 'Maharashtra Cricket Association Stadium'
 'Saurashtra Cricket Association Stadium' 'Holkar Cricket Stadium'
 'M.Chinnaswamy Stadium' 'Wankhede Stadium' 'Eden Gardens'
 'M Chinnaswamy Stadium' 'Feroz Shah Kotla'
 'Punjab Cricket Association IS Bindra Stadium, Mohali' 'Green Park'
 'Punjab Cricket Association IS Bindra Stadium'
 'Rajiv Gandhi International Stadium' 'MA Chidambaram Stadium'
 'Sawai Mansingh Stadium' 'Arun Jaitley Stadium'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'
 'Sheikh Zayed Stadium' 'Dubai International Cricket Stadium'
 'Sharjah Cricket Stadium' 'MA Chidambaram Stadium, Chepauk, Chennai'
 'Wankhede Stadium, Mumbai' 'Narendra Modi Stadium, Ahmedabad'
 'Arun Jaitley Stadium, Delhi' 'Zayed Cricket Stadium, Abu Dhabi'
 'Brabourne Stadium, Mumbai' 'Dr DY Patil Sports Academy, Mumbai'
 'Maharashtra Cricket Association Stadium, Pune' 'Eden Gardens, Kolkata'
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh'
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow'
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad'
 'M Chinnaswamy Stadium, Bengaluru' 'Barsapara Cricket Stadium, Guwahati'
 'Sawai Mansingh Stadium, Jaipur'
 'Himachal Pradesh Cricket Association Stadium, Dharamsala'
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam'
 'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh'
 'Punjab Cricket Association Stadium, Mohali'
 'MA Chidambaram Stadium, Chepauk' 'Dr DY Patil Sports Academy' 'Newlands'
 "St George's Park" 'Kingsmead' 'SuperSport Park' 'Buffalo Park'
 'New Wanderers Stadium' 'De Beers Diamond Oval' 'OUTsurance Oval'
 'Brabourne Stadium' 'Sardar Patel Stadium, Motera' 'Barabati Stadium'
 'Vidarbha Cricket Association Stadium, Jamtha'
 'Himachal Pradesh Cricket Association Stadium' 'Nehru Stadium'
 'Subrata Roy Sahara Stadium'
 'Shaheed Veer Narayan Singh International Stadium'
 'JSCA International Stadium Complex']

Unique values in column 'city':
['Hyderabad' 'Pune' 'Rajkot' 'Indore' 'Bengaluru' 'Mumbai' 'Kolkata'
 'Bangalore' 'Delhi' 'Chandigarh' 'Kanpur' 'Chennai' 'Jaipur'
 'Visakhapatnam' 'Abu Dhabi' nan 'Ahmedabad' 'Sharjah' 'Dubai'
 'Navi Mumbai' 'Lucknow' 'Guwahati' 'Dharamsala' 'Mohali' 'New Chandigarh'
 'Cape Town' 'Port Elizabeth' 'Durban' 'Centurion' 'East London'
 'Johannesburg' 'Kimberley' 'Bloemfontein' 'Cuttack' 'Nagpur' 'Kochi'
 'Raipur' 'Ranchi']

Unique values in column 'team1':
['Sunrisers Hyderabad' 'Rising Pune Supergiant' 'Gujarat Lions'
 'Kings XI Punjab' 'Royal Challengers Bangalore' 'Mumbai Indians'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Rajasthan Royals'
 'Chennai Super Kings' 'Delhi Capitals' 'Punjab Kings'
 'Lucknow Super Giants' 'Gujarat Titans' 'Royal Challengers Bengaluru'
 'Deccan Chargers' 'Kochi Tuskers Kerala' 'Pune Warriors'
 'Rising Pune Supergiants']

Unique values in column 'team2':
['Royal Challengers Bangalore' 'Mumbai Indians' 'Kolkata Knight Riders'
 'Rising Pune Supergiant' 'Delhi Daredevils' 'Gujarat Lions'
 'Sunrisers Hyderabad' 'Kings XI Punjab' 'Chennai Super Kings'
 'Rajasthan Royals' 'Delhi Capitals' 'Punjab Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Royal Challengers Bengaluru' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Rising Pune Supergiants']

Unique values in column 'toss_winner':
['Royal Challengers Bangalore' 'Rising Pune Supergiant'
 'Kolkata Knight Riders' 'Kings XI Punjab' 'Sunrisers Hyderabad'
 'Mumbai Indians' 'Gujarat Lions' 'Delhi Daredevils' 'Chennai Super Kings'
 'Rajasthan Royals' 'Delhi Capitals' 'Punjab Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Royal Challengers Bengaluru' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Rising Pune Supergiants']

Unique values in column 'toss_decision':
['field' 'bat']

Unique values in column 'winner':
['Sunrisers Hyderabad' 'Rising Pune Supergiant' 'Kolkata Knight Riders'
 'Kings XI Punjab' 'Royal Challengers Bangalore' 'Mumbai Indians'
 'Delhi Daredevils' 'Gujarat Lions' 'tie' 'Chennai Super Kings'
 'Rajasthan Royals' 'Delhi Capitals' 'no result' 'Punjab Kings'
 'Gujarat Titans' 'Lucknow Super Giants' 'Royal Challengers Bengaluru'
 'Deccan Chargers' 'Pune Warriors' 'Kochi Tuskers Kerala'
 'Rising Pune Supergiants']

Unique values in column 'player_of_match':
['Yuvraj Singh' 'SPD Smith' 'CA Lynn' 'GJ Maxwell' 'KM Jadhav'
 'Rashid Khan' 'N Rana' 'AR Patel' 'SV Samson' 'JJ Bumrah' 'SP Narine'
 'KA Pollard' 'AJ Tye' 'RV Uthappa' 'CJ Anderson' 'BA Stokes'
 'NM Coulter-Nile' 'B Kumar' 'CH Gayle' 'KS Williamson' 'JC Buttler'
 'SK Raina' 'MJ McClenaghan' 'MS Dhoni' 'HM Amla' 'G Gambhir'
 'LH Ferguson' 'KH Pandya' 'Sandeep Sharma' 'DA Warner' 'RG Sharma'
 'Mohammed Shami' 'RA Tripathi' 'RR Pant' 'JD Unadkat' 'LMP Simmons'
 'DR Smith' 'S Dhawan' 'MM Sharma' 'SS Iyer' 'WP Saha' 'KK Nair'
 'Mohammed Siraj' 'AT Rayudu' 'HV Patel' 'Washington Sundar' 'KV Sharma'
 'DJ Bravo' 'KL Rahul' 'SW Billings' 'UT Yadav' 'JJ Roy' 'B Stanlake'
 'SR Watson' 'AB de Villiers' 'JC Archer' 'AS Rajpoot' 'TG Southee'
 'SA Yadav' 'RA Jadeja' 'HH Pandya' 'Mujeeb Ur Rahman' 'Ishan Kishan'
 'Kuldeep Yadav' 'S Gopal' 'A Mishra' 'L Ngidi' 'F du Plessis'
 'AD Russell' 'Harbhajan Singh' 'MA Agarwal' 'PP Shaw' 'JM Bairstow'
 'SM Curran' 'AS Joseph' 'K Rabada' 'HF Gurney' 'DL Chahar' 'Imran Tahir'
 'KMA Paul' 'SL Malinga' 'R Ashwin' 'V Kohli' 'KK Ahmed' 'PA Patel'
 'VR Aaron' nan 'Shubman Gill' 'SO Hetmyer' 'MP Stoinis' 'S Nadeem'
 'CV Varun' 'CJ Jordan' 'Shivam Mavi' 'A Nortje' 'RD Gaikwad' 'R Tewatia'
 'YS Chahal' 'PK Garg' 'MK Pandey' 'TA Boult' 'KD Karthik' 'Q de Kock'
 'PJ Cummins' 'RD Chahar' 'MM Ali' 'D Padikkal' 'CH Morris' 'EJG Morgan'
 'Harpreet Brar' 'JR Hazlewood' 'KS Bharat' 'JO Holder' 'Kartik Tyagi'
 'VR Iyer' 'OF Smith' 'PWH de Silva' 'E Lewis' 'LS Livingstone'
 'Avesh Khan' 'Abhishek Sharma' 'Anuj Rawat' 'S Dube' 'Umran Malik'
 'DA Miller' 'Mukesh Choudhary' 'M Jansen' 'R Parag' 'Mohsin Khan'
 'RK Singh' 'TH David' 'YBK Jaiswal' 'DP Conway' 'MR Marsh' 'DR Sams'
 'SN Thakur' 'RM Patidar' 'Arshdeep Singh' 'MA Wood' 'B Sai Sudharsan'
 'NT Ellis' 'N Pooran' 'HC Brook' 'Sikandar Raza' 'C Green' 'I Sharma'
 'AM Rahane' 'A Manohar' 'J Little' 'M Pathirana' 'PD Salt' 'GD Phillips'
 'PN Mankad' 'P Simran Singh' 'WD Parnell' 'RR Rossouw' 'Akash Madhwal'
 'Mustafizur Rahman' 'MP Yadav' 'Shashank Singh' 'R Shepherd'
 'Yash Thakur' 'Nithish Kumar Reddy' 'TM Head' 'R Sai Kishore'
 'J Fraser-McGurk' 'WG Jacks' 'Simarjeet Singh' 'MA Starc' 'Shahbaz Ahmed'
 'Noor Ahmad' 'Ashutosh Sharma' 'M Prasidh Krishna' 'Ashwani Kumar'
 'VG Arora' 'DS Rathi' 'Priyansh Arya' 'AK Markram' 'Mukesh Kumar'
 'V Suryavanshi' 'RD Rickelton' 'D Brevis' 'H Klaasen' 'JP Inglis'
 'JM Sharma' 'Suyash Sharma' 'Sameer Rizvi' 'BB McCullum' 'MEK Hussey'
 'MF Maharoof' 'MV Boucher' 'DJ Hussey' 'V Sehwag' 'ML Hayden' 'YK Pathan'
 'KC Sangakkara' 'JDP Oram' 'AC Gilchrist' 'SM Katich' 'ST Jayasuriya'
 'GD McGrath' 'SE Marsh' 'SA Asnodkar' 'R Vinay Kumar' 'IK Pathan'
 'SM Pollock' 'Sohail Tanvir' 'S Sreesanth' 'A Nehra' 'SC Ganguly'
 'CRD Fernando' 'L Balaji' 'Shoaib Akhtar' 'DPMD Jayawardene' 'GC Smith'
 'M Ntini' 'SP Goswami' 'A Kumble' 'JA Morkel' 'P Kumar' 'Umar Gul'
 'SR Tendulkar' 'R Dravid' 'DL Vettori' 'RP Singh' 'M Muralitharan'
 'RS Bopara' 'PP Ojha' 'TM Dilshan' 'HH Gibbs' 'DP Nannes' 'JP Duminy'

### Number of Missing Values Each Column

In [ ]:
df.isnull().sum()

match_id                  0
date                      0
season                    0
event                     0
venue                     0
city                  12397
team1                     0
team2                     0
toss_winner               0
toss_decision             0
winner                    0
win_by_runs          156126
win_by_wickets       138527
player_of_match         828
innings                   0
batting_team              0
over                      0
ball                      0
batter                    0
bowler                    0
non_striker               0
runs_batter               0
runs_extras               0
runs_total                0
extras_wides              0
extras_noballs            0
extras_byes               0
extras_legbyes            0
wicket_kind          275267
wicket_player_out    275267
dtype: int64

### Number of Duplicate Rows

In [ ]:
df.duplicated().sum()

np.int64(0)

## 3. Data Preprocessing

3.1 Date Preprocessing

* Convert Date from Object Type to Date Time format

* Sort the data according to the date

In [ ]:
df['date'] = pd.to_datetime(df['date'])

In [ ]:
df = df.sort_values(by='date').reset_index(drop=True)
display(df.head())

,match_id,date,season,event,venue,city,team1,team2,toss_winner,toss_decision,...,non_striker,runs_batter,runs_extras,runs_total,extras_wides,extras_noballs,extras_byes,extras_legbyes,wicket_kind,wicket_player_out
0,335982,2008-04-18,2007/08,Indian Premier League,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,BB McCullum,0,1,1,0,0,0,1,NaN,NaN
1,335982,2008-04-18,2007/08,Indian Premier League,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,JH Kallis,2,0,2,0,0,0,0,NaN,NaN
2,335982,2008-04-18,2007/08,Indian Premier League,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,JH Kallis,1,0,1,0,0,0,0,NaN,NaN
3,335982,2008-04-18,2007/08,Indian Premier League,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,W Jaffer,0,0,0,0,0,0,0,NaN,NaN
4,335982,2008-04-18,2007/08,Indian Premier League,M Chinnaswamy Stadium,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,W Jaffer,0,1,1,0,0,0,1,NaN,NaN

3.2 Season Column Preprocessing

In [ ]:
df['season'].unique()

array(['2007/08', '2009', '2009/10', '2011', 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, '2019', '2020/21', '2021', 2021, 2022,
       2023, 2024, 2025, '2025', 2026], dtype=object)

* Data Type Mismatch -> The same season appears as both an integer and a string (e.g., '2001' as string and 2001 as int)


* Convert all to string data type.

In [ ]:
df['season'] = df['season'].astype(str)
df['season'].unique()

array(['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022',
       '2023', '2024', '2025', '2026'], dtype=object)

3.3 Event Preprocessing

* Since all data belongs to the same event (i.e., Indian Premier League)

* There is no use of having it. We will remove it.

In [ ]:
df = df.drop(columns=['event'])
print(df.columns)

Index(['match_id', 'date', 'season', 'venue', 'city', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'innings', 'batting_team', 'over',
       'ball', 'batter', 'bowler', 'non_striker', 'runs_batter', 'runs_extras',
       'runs_total', 'extras_wides', 'extras_noballs', 'extras_byes',
       'extras_legbyes', 'wicket_kind', 'wicket_player_out'],
      dtype='object')

3.4 Venue Preprocessing

In [ ]:
df['venue'].unique()

array(['M Chinnaswamy Stadium', 'Feroz Shah Kotla',
       'Punjab Cricket Association Stadium, Mohali', 'Eden Gardens',
       'Wankhede Stadium', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Brabourne Stadium, Mumbai',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Maharashtra Cricket Association Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Rajiv Gandhi International Stadium', 'MA Chidambaram Stadium',
       'Arun Jaitley Stadium', 'MA Chidambaram Stadium, Chepauk, Chennai',
       'Wankhede Stadium, Mumbai', 'Narendra Modi Stadium, Ahmedabad',
       'Arun Jaitley Stadium, Delhi', 'Zayed Cricket Stadium, Abu Dhabi',
       'Dr DY Patil Sports Academy, Mumbai',
       'Maharashtra Cricket Association Stadium, Pune',
       'Eden Gardens, Kolkata',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
       'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
       'M Chinnaswamy Stadium, Bengaluru',
       'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
       'Barsapara Cricket Stadium, Guwahati',
       'Sawai Mansingh Stadium, Jaipur',
       'Himachal Pradesh Cricket Association Stadium, Dharamsala',
       'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
       'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh'],
      dtype=object)

* Same Stadium, Different Names (e.g., "M Chinnaswamy Stadium",
"M.Chinnaswamy Stadium",
"M Chinnaswamy Stadium, Bengaluru").

* Also, we have a separate column for city, so it's better to remove the city name present in the stadium name.

In [ ]:
venue_map = {

    # Chinnaswamy Stadium
    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    "M Chinnaswamy Stadium, Bengaluru": "M Chinnaswamy Stadium",

    # Arun Jaitley / Feroz Shah Kotla
    "Feroz Shah Kotla": "Arun Jaitley Stadium",
    "Arun Jaitley Stadium, Delhi": "Arun Jaitley Stadium",

    # MA Chidambaram Stadium
    "MA Chidambaram Stadium, Chepauk": "MA Chidambaram Stadium",
    "MA Chidambaram Stadium, Chepauk, Chennai": "MA Chidambaram Stadium",

    # Rajiv Gandhi International Stadium
    "Rajiv Gandhi International Stadium, Uppal": "Rajiv Gandhi International Stadium",
    "Rajiv Gandhi International Stadium, Uppal, Hyderabad": "Rajiv Gandhi International Stadium",

    # Wankhede Stadium
    "Wankhede Stadium, Mumbai": "Wankhede Stadium",

    # Punjab Cricket Association Stadium / IS Bindra Stadium
    "Punjab Cricket Association Stadium, Mohali": "Punjab Cricket Association IS Bindra Stadium",
    "Punjab Cricket Association IS Bindra Stadium, Mohali": "Punjab Cricket Association IS Bindra Stadium",
    "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh": "Punjab Cricket Association IS Bindra Stadium",

    # Dr DY Patil
    "Dr DY Patil Sports Academy, Mumbai": "Dr DY Patil Sports Academy",

    # ACA-VDCA Stadium
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam":
        "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium",

    # Maharashtra Cricket Association Stadium
    "Maharashtra Cricket Association Stadium, Pune":
        "Maharashtra Cricket Association Stadium",

    # Eden Gardens
    "Eden Gardens, Kolkata": "Eden Gardens",


    # Modi Stadium
    "Sardar Patel Stadium, Motera": "Narendra Modi Stadium",

    "Narendra Modi Stadium, Ahmedabad": "Narendra Modi Stadium",

    # Sheikh Zayed Stadium
    "Zayed Cricket Stadium, Abu Dhabi": "Sheikh Zayed Stadium",

    # HPCA Stadium
    "Himachal Pradesh Cricket Association Stadium, Dharamsala":
        "Himachal Pradesh Cricket Association Stadium",

    # Sawai Mansingh Stadium
    "Sawai Mansingh Stadium, Jaipur": "Sawai Mansingh Stadium",

    # Ekana Stadium
    "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow":
        "Ekana Cricket Stadium",

    # Maharaja Yadavindra Singh Stadium
    "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur":
        "Maharaja Yadavindra Singh International Cricket Stadium",

    "Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh":
        "Maharaja Yadavindra Singh International Cricket Stadium",

    #Brabourne Stadium
    "Brabourne Stadium, Mumbai": "Brabourne Stadium",

    #Barsapara Cricket Stadium
    "Barsapara Cricket Stadium, Guwahati": "Barsapara Cricket Stadium",

    #Vidarbha Cricket Association Stadium
    "Vidarbha Cricket Association Stadium, Jamtha":
        "Vidarbha Cricket Association Stadium",
}

In [ ]:
df["venue"] = df["venue"].replace(venue_map)
df["venue"].unique()

array(['M Chinnaswamy Stadium', 'Arun Jaitley Stadium',
       'Punjab Cricket Association IS Bindra Stadium', 'Eden Gardens',
       'Wankhede Stadium', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium', 'MA Chidambaram Stadium',
       'Dr DY Patil Sports Academy', 'Newlands', "St George's Park",
       'Kingsmead', 'SuperSport Park', 'Buffalo Park',
       'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium', 'Narendra Modi Stadium',
       'Barabati Stadium', 'Vidarbha Cricket Association Stadium',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Maharashtra Cricket Association Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'Ekana Cricket Stadium', 'Barsapara Cricket Stadium',
       'Maharaja Yadavindra Singh International Cricket Stadium'],
      dtype=object)

3.5 City Preprocessing

In [ ]:
df['city'].isnull().sum()

np.int64(12397)

* City column has 12397 missing values.
* Fill the values based on the stadium name where it is located.

In [ ]:
venue_city_map = {

    # India
    "M Chinnaswamy Stadium": "Bengaluru",
    "Arun Jaitley Stadium": "Delhi",
    "Punjab Cricket Association IS Bindra Stadium": "Mohali",
    "Eden Gardens": "Kolkata",
    "Wankhede Stadium": "Mumbai",
    "Sawai Mansingh Stadium": "Jaipur",
    "Rajiv Gandhi International Stadium": "Hyderabad",
    "MA Chidambaram Stadium": "Chennai",
    "Dr DY Patil Sports Academy": "Mumbai",
    "Brabourne Stadium": "Mumbai",
    "Narendra Modi Stadium": "Ahmedabad",
    "Barabati Stadium": "Cuttack",
    "Vidarbha Cricket Association Stadium": "Nagpur",
    "Himachal Pradesh Cricket Association Stadium": "Dharamsala",
    "Nehru Stadium": "Kochi",
    "Holkar Cricket Stadium": "Indore",
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "Visakhapatnam",
    "Subrata Roy Sahara Stadium": "Pune",
    "Maharashtra Cricket Association Stadium": "Pune",
    "Shaheed Veer Narayan Singh International Stadium": "Raipur",
    "JSCA International Stadium Complex": "Ranchi",
    "Saurashtra Cricket Association Stadium": "Rajkot",
    "Green Park": "Kanpur",
    "Ekana Cricket Stadium": "Lucknow",
    "Barsapara Cricket Stadium": "Guwahati",
    "Maharaja Yadavindra Singh International Cricket Stadium": "Mullanpur",

    # UAE
    "Sheikh Zayed Stadium": "Abu Dhabi",
    "Sharjah Cricket Stadium": "Sharjah",
    "Dubai International Cricket Stadium": "Dubai",

    # South Africa (IPL 2009)
    "Newlands": "Cape Town",
    "St George's Park": "Gqeberha",
    "Kingsmead": "Durban",
    "SuperSport Park": "Centurion",
    "Buffalo Park": "East London",
    "New Wanderers Stadium": "Johannesburg",
    "De Beers Diamond Oval": "Kimberley",
    "OUTsurance Oval": "Bloemfontein"
}

In [ ]:
df["city"] = df["city"].fillna(df["venue"].map(venue_city_map))

In [ ]:
df['city'].isnull().sum()

np.int64(0)

In [ ]:
df['city'].unique()

array(['Bangalore', 'Delhi', 'Chandigarh', 'Kolkata', 'Mumbai', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Rajkot', 'Kanpur', 'Bengaluru',
       'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali', 'New Chandigarh'],
      dtype=object)

* Same city with different names (e.g., Bangalore, Bengaluru)

* The stadium is located in Mohali (Punjab), although older IPL datasets often use Chandigarh.

In [ ]:
city_map = {
    "Bangalore": "Bengaluru",
    "Chandigarh": "Mohali"
}

In [ ]:
df["city"] = df["city"].replace(city_map)

In [ ]:
df['city'].unique()

array(['Bengaluru', 'Delhi', 'Mohali', 'Kolkata', 'Mumbai', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Rajkot', 'Kanpur', 'Navi Mumbai',
       'Lucknow', 'Guwahati', 'New Chandigarh'], dtype=object)

3.6 Team Name Preprocessing

In [ ]:
df['team1'].unique()

array(['Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [ ]:
df['team2'].unique()

array(['Kolkata Knight Riders', 'Rajasthan Royals', 'Chennai Super Kings',
       'Deccan Chargers', 'Royal Challengers Bangalore',
       'Kings XI Punjab', 'Delhi Daredevils', 'Mumbai Indians',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [ ]:
df['toss_winner'].unique()

array(['Royal Challengers Bangalore', 'Rajasthan Royals',
       'Chennai Super Kings', 'Deccan Chargers', 'Mumbai Indians',
       'Kings XI Punjab', 'Kolkata Knight Riders', 'Delhi Daredevils',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [ ]:
df['winner'].unique()

array(['Kolkata Knight Riders', 'Delhi Daredevils', 'Chennai Super Kings',
       'Royal Challengers Bangalore', 'Rajasthan Royals',
       'Kings XI Punjab', 'Deccan Chargers', 'Mumbai Indians', 'tie',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'no result',
       'Sunrisers Hyderabad', 'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [ ]:
df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Rajasthan Royals', 'Kings XI Punjab', 'Delhi Daredevils',
       'Chennai Super Kings', 'Deccan Chargers', 'Mumbai Indians',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

* Franchise Name Inconsistency

In [ ]:
team_map = {
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru",
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings",
    "Rising Pune Supergiants": "Rising Pune Supergiant"
}

In [ ]:
cols = ['team1', 'team2', 'toss_winner', 'winner', 'batting_team']

for col in cols:
    df[col] = df[col].replace(team_map)

3.7 Toss Decision Preprocessing

* No preprocessing required because there are no null values and no data inconsistency.

3.8 Player Name Preprocessing

In [ ]:
columns_to_check = ['player_of_match', 'batter', 'bowler', 'non_striker', 'wicket_kind', 'wicket_player_out']

for col in columns_to_check:
    print(f"\nUnique values in '{col}':")
    print(df[col].unique())

Unique values in 'player_of_match':
['BB McCullum' 'MF Maharoof' 'MEK Hussey' 'DJ Hussey' 'MV Boucher'
 'SR Watson' 'V Sehwag' 'ML Hayden' 'YK Pathan' 'KC Sangakkara' 'JDP Oram'
 'SM Katich' 'AC Gilchrist' 'MS Dhoni' 'ST Jayasuriya' 'GD McGrath'
 'SA Asnodkar' 'SE Marsh' 'IK Pathan' 'P Kumar' 'Sohail Tanvir'
 'SM Pollock' 'S Sreesanth' 'A Nehra' 'SC Ganguly' 'L Balaji'
 'Shoaib Akhtar' 'A Mishra' 'DPMD Jayawardene' 'GC Smith' 'DJ Bravo'
 'M Ntini' 'SP Goswami' 'A Kumble' 'KD Karthik' 'JA Morkel'
 'R Vinay Kumar' 'Umar Gul' 'SK Raina' 'CRD Fernando' 'R Dravid'
 'SR Tendulkar' 'RP Singh' 'DL Vettori' 'M Muralitharan' 'CH Gayle'
 'AB de Villiers' 'RS Bopara' 'PP Ojha' 'TM Dilshan' 'HH Gibbs'
 'DP Nannes' 'Yuvraj Singh' 'JP Duminy' 'SB Jakati' 'JH Kallis'
 'G Gambhir' 'RG Sharma' 'A Singh' 'S Badrinath' 'DR Smith'
 'Harbhajan Singh' 'LRPL Taylor' 'R Bhatia' 'SK Warne' 'B Lee' 'BJ Hodge'
 'LR Shukla' 'MK Pandey' 'AD Mathews' 'WPUJC Vaas' 'MK Tiwary' 'A Symonds'
 'AA Jhunjhunwala' 'J Theron' 'RV Uthappa' 'AC Voges' 'KM Jadhav'
 'NV Ojha' 'DA Warner' 'SL Malinga' 'M Vijay' 'KP Pietersen' 'AT Rayudu'
 'PD Collingwood' 'MJ Lumb' 'TL Suman' 'RJ Harris' 'PP Chawla'
 'Harmeet Singh' 'R Ashwin' 'KA Pollard' 'JD Unadkat' 'R McLaren'
 'M Kartik' 'DE Bollinger' 'S Anirudha' 'SK Trivedi' 'SB Wagh' 'MD Mishra'
 'PC Valthaty' 'DW Steyn' 'S Sohal' 'MM Patel' 'V Kohli' 'I Sharma'
 'J Botha' 'Iqbal Abdulla' 'P Parameswaran' 'R Sharma' 'BA Bhatt'
 'MR Marsh' 'S Aravind' 'WP Saha' 'S Dhawan' nan 'JEC Franklin' 'RE Levi'
 'AM Rahane' 'SPD Smith' 'RA Jadeja' 'MN Samuels' 'M Morkel'
 'AD Mascarenhas' 'F du Plessis' 'Shakib Al Hasan' 'JD Ryder' 'SP Narine'
 'S Nadeem' 'KMDN Kulasekara' 'CL White' 'Mandeep Singh' 'P Negi'
 'Azhar Mahmood' 'BW Hilfenhaus' 'A Chandila' 'UT Yadav' 'MS Bisla'
 'GH Vihari' 'M Vohra' 'AJ Finch' 'JP Faulkner' 'MS Gony' 'DA Miller'
 'SV Samson' 'DJG Sammy' 'MG Johnson' 'KK Cooper' 'PA Patel' 'AP Tare'
 'LJ Wright' 'YS Chahal' 'GJ Maxwell' 'CA Lynn' 'MM Sharma'
 'Sandeep Sharma' 'PV Tambe' 'B Kumar' 'KK Nair' 'CJ Anderson' 'AR Patel'
 'LMP Simmons' 'GJ Bailey' 'DJ Hooda' 'MA Agarwal' 'AD Russell' 'SS Iyer'
 'MA Starc' 'VR Aaron' 'TA Boult' 'NM Coulter-Nile' 'EJG Morgan'
 'HH Pandya' 'MC Henriques' 'Z Khan' 'MJ McClenaghan' 'Q de Kock'
 'Mustafizur Rahman' 'SA Yadav' 'AB Dinda' 'CH Morris' 'CR Brathwaite'
 'RR Pant' 'MP Stoinis' 'A Zampa' 'KH Pandya' 'HM Amla' 'BCJ Cutting'
 'N Rana' 'Rashid Khan' 'JJ Bumrah' 'AJ Tye' 'BA Stokes' 'KS Williamson'
 'JC Buttler' 'LH Ferguson' 'Mohammed Shami' 'RA Tripathi'
 'Mohammed Siraj' 'HV Patel' 'Washington Sundar' 'KV Sharma' 'KL Rahul'
 'SW Billings' 'B Stanlake' 'JJ Roy' 'JC Archer' 'AS Rajpoot' 'TG Southee'
 'Mujeeb Ur Rahman' 'Ishan Kishan' 'Kuldeep Yadav' 'S Gopal' 'L Ngidi'
 'PP Shaw' 'JM Bairstow' 'SM Curran' 'AS Joseph' 'HF Gurney' 'K Rabada'
 'DL Chahar' 'KMA Paul' 'Imran Tahir' 'KK Ahmed' 'Shubman Gill'
 'SO Hetmyer' 'Shivam Mavi' 'PK Garg' 'R Tewatia' 'A Nortje' 'CJ Jordan'
 'CV Varun' 'RD Gaikwad' 'PJ Cummins' 'RD Chahar' 'MM Ali' 'D Padikkal'
 'Harpreet Brar' 'Kartik Tyagi' 'JO Holder' 'JR Hazlewood' 'KS Bharat'
 'VR Iyer' 'OF Smith' 'PWH de Silva' 'E Lewis' 'LS Livingstone'
 'Avesh Khan' 'Anuj Rawat' 'Abhishek Sharma' 'S Dube' 'Umran Malik'
 'Mukesh Choudhary' 'M Jansen' 'R Parag' 'Mohsin Khan' 'RK Singh'
 'TH David' 'YBK Jaiswal' 'DP Conway' 'DR Sams' 'SN Thakur' 'RM Patidar'
 'MA Wood' 'Arshdeep Singh' 'B Sai Sudharsan' 'NT Ellis' 'N Pooran'
 'HC Brook' 'Sikandar Raza' 'C Green' 'A Manohar' 'J Little' 'PD Salt'
 'M Pathirana' 'GD Phillips' 'P Simran Singh' 'PN Mankad' 'WD Parnell'
 'RR Rossouw' 'Akash Madhwal' 'MP Yadav' 'Shashank Singh' 'Yash Thakur'
 'R Shepherd' 'Nithish Kumar Reddy' 'TM Head' 'R Sai Kishore'
 'J Fraser-McGurk' 'WG Jacks' 'Simarjeet Singh' 'Shahbaz Ahmed'
 'Noor Ahmad' 'Ashutosh Sharma' 'M Prasidh Krishna' 'Ashwani Kumar'
 'VG Arora' 'DS Rathi' 'Priyansh Arya' 'AK Markram' 'Mukesh Kumar'
 'V Suryavanshi' 'RD Rickelton' 'Sameer Rizvi' 'H Klaasen' 'D Brevis'
 'JP Inglis' 'JM Sharma' 'Suyash Sharma' 'JA Duffy' 'N Burger'
 'C Connolly' 'Ravi Bishnoi' 'MD Choudhary' 'PP Hinge' 'E Malinga'
 'T Stubbs' 'Tilak Varma' 'D Ferreira']

Unique values in 'batter':
['SC Ganguly' 'W Jaffer' 'JH Kallis' 'CL White' 'MV Boucher' 'BB McCullum'
 'Mohammad Hafeez' 'R Dravid' 'V Kohli' 'P Kumar' 'Z Khan' 'SB Joshi'
 'AA Noffke' 'B Akhil' 'RT Ponting' 'DJ Hussey' 'M Kaif' 'RA Jadeja'
 'M Rawat' 'D Salunkhe' 'DS Lehmann' 'SK Warne' 'IK Pathan' 'YK Pathan'
 'T Kohli' 'SM Katich' 'SR Watson' 'G Gambhir' 'SK Trivedi' 'S Dhawan'
 'V Sehwag' 'KC Sangakkara' 'MEK Hussey' 'JDP Oram' 'SK Raina'
 'S Badrinath' 'ML Hayden' 'PA Patel' 'MS Dhoni' 'Yuvraj Singh' 'JR Hopes'
 'K Goel' 'A Symonds' 'AS Yadav' 'SB Styris' 'RP Singh' 'SB Bangar'
 'WPUJC Vaas' 'Y Venugopal Rao' 'VVS Laxman' 'AC Gilchrist' 'WP Saha'
 'RG Sharma' 'LR Shukla' 'RV Uthappa' 'AM Nayar' 'PR Shah' 'SM Pollock'
 'Harbhajan Singh' 'ST Jayasuriya' 'DJ Thornely' 'L Ronchi' 'LRPL Taylor'
 'S Chanderpaul' 'Kamran Akmal' 'PP Chawla' 'DPMD Jayawardene' 'S Sohal'
 'B Lee' 'WA Mota' 'Shahid Afridi' 'DJ Bravo' 'MA Khote' 'A Nehra'
 'GC Smith' 'Pankaj Singh' 'SS Tiwary' 'DS Kulkarni' 'VRV Singh'
 'S Sreesanth' 'RR Sarwan' 'AB Agarkar' 'M Kartik' 'I Sharma'
 'R Vinay Kumar' 'MF Maharoof' 'R Bhatia' 'MK Tiwary' 'VY Mahesh'
 'KD Karthik' 'Shoaib Malik' 'TM Srivastava' 'AM Rahane' 'B Chipli'
 'DW Steyn' 'MK Pandey' 'DB Das' 'SA Asnodkar' 'Sohail Tanvir'
 'Salman Butt' 'AB Dinda' 'Umar Gul' 'BJ Hodge' 'DNT Zoysa'
 'D Kalyankrishna' 'HH Gibbs' 'SE Marsh' 'JA Morkel' 'AB de Villiers'
 'S Vidyut' 'SP Fleming' 'Misbah-ul-Haq' 'MS Gony' 'Joginder Sharma'
 'GD McGrath' 'Mohammad Asif' 'PJ Sangwan' 'M Muralitharan' 'M Ntini'
 'YV Takawale' 'RR Raje' 'DT Patil' 'A Kumble' 'S Anirudha' 'MM Patel'
 'T Taibu' 'A Chopra' 'CK Kapugedera' 'J Arunkumar' 'PP Ojha'
 'DB Ravi Teja' 'U Kaul' 'AD Mascarenhas' 'NK Patel' 'TM Dilshan'
 'A Mishra' 'LA Pomersbach' 'Iqbal Abdulla' 'SR Tendulkar'
 'PM Sarvesh Kumar' 'DP Vijaykumar' 'Shoaib Akhtar' 'Abdur Razzak'
 'LPC Silva' 'H Das' 'SP Goswami' 'DR Smith' 'SD Chitnis' 'CRD Fernando'
 'VS Yeligati' 'L Balaji' 'A Mukund' 'Younis Khan' 'RR Powar'
 'KP Pietersen' 'JD Ryder' 'T Thushara' 'T Henderson' 'Kamran Khan'
 'JP Duminy' 'A Flintoff' 'MC Henriques' 'RS Bopara' 'CH Gayle'
 'R Bishnoi' 'KV Sharma' 'FH Edwards' 'AS Raut' 'RJ Quiney'
 'Yashpal Singh' 'PC Valthaty' 'M Manhas' 'AA Bilakhia' 'BAW Mendis'
 'AN Ghosh' 'DL Vettori' 'MN van Wyk' 'RE van der Merwe' 'TL Suman'
 'Shoaib Ahmed' 'KP Appanna' 'GR Napier' 'SB Jakati' 'M Vijay' 'DA Warner'
 'SM Harwood' 'LA Carseldine' 'NV Ojha' 'RJ Harris' 'D du Preez'
 'M Morkel' 'AD Mathews' 'J Botha' 'SL Malinga' 'C Nanda'
 'Mashrafe Mortaza' 'A Singh' 'GJ Bailey' 'Y Nagar' 'AB McDonald'
 'R Ashwin' 'SS Shaikh' 'Mohammad Ashraful' 'Jaskaran Singh'
 'Anirudh Singh' 'OA Shah' 'CA Pujara' 'MS Bisla' 'YA Abdulla' 'AT Rayudu'
 'R McLaren' 'R Sathish' 'AP Tare' 'A Uniyal' 'P Dogra' 'AA Jhunjhunwala'
 'JM Kemp' 'S Tyagi' 'EJG Morgan' 'SE Bond' 'RS Gavaskar' 'KA Pollard'
 'S Ladda' 'DP Nannes' 'DR Martyn' 'S Narwal' 'MJ Lumb' 'AB Barath'
 'Bipul Sharma' 'AC Voges' 'FY Fazal' 'J Theron' 'MD Mishra' 'UT Yadav'
 'SJ Srivastava' 'KM Jadhav' 'R Sharma' 'Mandeep Singh' 'KB Arun Karthik'
 'KAJ Roach' 'SW Tait' 'CK Langeveldt' 'PD Collingwood' 'VS Malik'
 'A Mithun' 'AP Dole' 'AN Ahmed' 'RS Sodhi' 'S Sriram' 'DE Bollinger'
 'B Sumanth' 'C Madan' 'AG Paunikar' 'MR Marsh' 'AJ Finch' 'STR Binny'
 'Harmeet Singh' 'RV Gomez' 'MA Agarwal' 'AUK Pathan' 'DT Christian'
 'IR Jaggi' 'Sunny Singh' 'NJ Rimmington' 'UBT Chand' 'DJ Jacobs'
 'AL Menaria' 'WD Parnell' 'JJ van der Wath' 'R Ninan' 'S Aravind'
 'MS Wade' 'Shakib Al Hasan' 'JEC Franklin' 'AC Thomas' 'SB Wagh'
 'TD Paine' 'DH Yagnik' 'BJ Haddin' 'S Randiv' 'NLTC Perera' 'NL McCullum'
 'JE Taylor' 'J Syed Mohammad' 'TR Birt' 'RN ten Doeschate'
 'Harpreet Singh' 'AG Murtaza' 'M Klinger' 'AC Blizzard' 'I Malhotra'
 'L Ablish' 'CA Ingram' 'S Nadeem' 'CJ Ferguson' 'P Parameswaran'
 'VR Aaron' 'ND Doshi' 'AA Chavan' 'B Kumar' 'Y Gnaneswara Rao' 'S Rana'
 'BA Bhatt' 'RE Levi' 'F du Plessis' 'GJ Maxwell' 'KK Cooper'
 'JP Faulkner' 'SPD Smith' 'MN Samuels' 'SA Yadav' 'DAJ Bracewell'
 'Ankit Sharma' 'DJ Harris' 'HV Patel' 'SP Narine' 'GB Hogg' 'RR Bhatkal'
 'CJ McKay' 'DA Miller' 'N Saini' 'Azhar Mahmood' 'P Negi' 'RJ Peterson'
 'KMDN Kulasekara' 'A Ashish Reddy' 'V Pratap Singh' 'MJ Clarke'
 'BB Samantray' 'Gurkeerat Singh' 'PA Reddy' 'AP Majumdar' 'K Upadhyay'
 'P Awana' 'AD Russell' 'CA Lynn' 'A Chandila' 'Sunny Gupta' 'MC Juneja'
 'KK Nair' 'GH Vihari' 'AS Rajpoot' 'B Laughlin' 'R Shukla' 'MDKJ Perera'
 'JD Unadkat' 'M Vohra' 'Mohammed Shami' 'BMAJ Mendis' 'CH Morris'
 'R Rampaul' 'SV Samson' 'KL Rahul' 'BJ Rohrer' 'SMSM Senanayake'
 'MG Johnson' 'R Dhawan' 'Q de Kock' 'LJ Wright' 'IC Pandey'
 'X Thalaivan Sargunam' 'DJG Sammy' 'KW Richardson' 'MM Sharma'
 'CM Gautam' 'Parvez Rasool' 'UA Birla' 'Sandeep Sharma' 'S Kaul'
 'Sachin Baby' 'PV Tambe' 'NM Coulter-Nile' 'CJ Anderson' 'NJ Maddinson'
 'AR Patel' 'JDS Neesham' 'JJ Bumrah' 'TG Southee' 'MA Starc' 'BR Dunk'
 'RR Rossouw' 'YS Chahal' 'Shivam Sharma' 'LMP Simmons' 'VH Zol'
 'Imran Tahir' 'BCJ Cutting' 'BE Hendricks' 'R Tewatia' 'S Gopal'
 'M de Lange' 'JO Holder' 'Karanveer Singh' 'SS Iyer' 'Anureet Singh'
 'DJ Hooda' 'KS Williamson' 'SA Abbott' 'J Suchith' 'D Wiese' 'HH Pandya'
 'SN Khan' 'MJ McClenaghan' 'DJ Muthuswami' 'PJ Cummins' 'RG More'
 'SN Thakur' 'JC Buttler' 'CR Brathwaite' 'MP Stoinis' 'Ishan Kishan'
 'C Munro' 'P Sahu' 'KH Pandya' 'AD Nath' 'MJ Guptill' 'KJ Abbott'
 'TM Head' 'M Ashwin' 'NS Naik' 'RR Pant' 'SW Billings' 'PSP Handscomb'
 'KC Cariappa' 'Swapnil Singh' 'UT Khawaja' 'J Yadav' 'HM Amla'
 'F Behardien' 'A Zampa' 'BB Sran' 'N Rana' 'S Kaushik' 'ER Dwivedi'
 'CJ Jordan' 'TS Mills' 'A Choudhary' 'BA Stokes' 'JJ Roy' 'Vishnu Vinod'
 'CR Woakes' 'Basil Thampi' 'RA Tripathi' 'DL Chahar' 'Rashid Khan'
 'V Shankar' 'RD Chahar' 'LH Ferguson' 'C de Grandhomme' 'AF Milne'
 'S Badree' 'Mohammad Nabi' 'AJ Tye' 'K Rabada' 'Kuldeep Yadav'
 'Washington Sundar' 'DM Bravo' 'AR Bawne' 'SP Jackson' 'Ankit Soni'
 'TA Boult' 'MA Wood' 'E Lewis' 'RK Singh' 'DJM Short' 'K Gowtham'
 'TK Curran' 'B Stanlake' 'M Markande' 'Mujeeb Ur Rahman' 'Shubman Gill'
 'Shivam Mavi' 'A Dananjaya' 'Mohammed Siraj' 'H Klaasen' 'JC Archer'
 'RK Bhui' 'PP Shaw' 'LE Plunkett' 'Mustafizur Rahman' 'AD Hales'
 'MK Lomror' 'DR Shorey' 'MM Ali' 'M Prasidh Krishna' 'P Chopra'
 'Abhishek Sharma' 'JPR Scantlebury-Searles' 'IS Sodhi' 'SO Hetmyer'
 'S Dube' 'Navdeep Saini' 'KMA Paul' 'Rasikh Salam' 'JM Bairstow'
 'N Pooran' 'P Ray Barman' 'Avesh Khan' 'S Lamichhane' 'SM Curran'
 'GC Viljoen' 'HF Gurney' 'SD Lad' 'AS Joseph' 'MJ Santner' 'R Parag'
 'JL Denly' 'LS Livingstone' 'KK Ahmed' 'AJ Turner' 'Harpreet Brar'
 'SE Rutherford' 'Y Prithvi Raj' 'P Simran Singh' 'JL Pattinson'
 'A Nortje' 'D Padikkal' 'JR Philippe' 'PK Garg' 'T Natarajan'
 'RD Gaikwad' 'YBK Jaiswal' 'Abdul Samad' 'KL Nagarkoti' 'Ravi Bishnoi'
 'I Udana' 'CV Varun' 'Arshdeep Singh' 'SS Cottrell' 'Kartik Tyagi'
 'N Jagadeesan' 'AT Carey' 'T Banton' 'TU Deshpande' 'P Dubey'
 'Shahbaz Ahmed' 'DR Sams' 'RM Patidar' 'KA Jamieson' 'M Jansen'
 'M Shahrukh Khan' 'JA Richardson' 'Lalit Yadav' 'Virat Singh' 'FA Allen'
 'C Sakariya' 'DJ Malan' 'Anmolpreet Singh' 'VR Iyer' 'KS Bharat'
 'PWH de Silva' 'AK Markram' 'TH David' 'T Shamsi' 'NT Ellis' 'TL Seifert'
 'GD Phillips' 'GHS Garton' 'RV Patel' 'K Yadav' 'Anuj Rawat' 'DP Conway'
 'PBB Rajapaksa' 'RA Bawa' 'OF Smith' 'Tilak Varma' 'R Powell' 'A Manohar'
 'A Badoni' 'PVD Chameera' 'R Shepherd' 'DJ Willey' 'D Pretorius'
 'VG Arora' 'Mukesh Choudhary' 'JM Sharma' 'Umran Malik' 'D Brevis'
 'B Sai Sudharsan' 'Ramandeep Singh' 'HE van der Dussen' 'SS Prabhudessai'
 'Akash Deep' 'JR Hazlewood' 'KR Sen' 'Aman Hakim Khan' 'HR Shokeen'
 'Yash Dayal' 'DJ Mitchell' 'Shashank Singh' 'Harshit Rana' 'B Indrajith'
 'Mohsin Khan' 'M Theekshana' 'Simarjeet Singh' 'AS Roy'
 'Fazalhaq Farooqi' 'K Kartikeya' 'RP Meredith' 'KS Sharma' 'T Stubbs'
 'R Sanjay Yadav' 'A Tomar' 'PN Mankad' 'OC McCoy' 'KR Mayers'
 'Mukesh Kumar' 'Sikandar Raza' 'Rahmanullah Gurbaz' 'N Wadhera'
 'Arshad Khan' 'C Green' 'AU Rashid' 'HC Brook' 'Abishek Porel'
 'Dhruv Jurel' 'MG Bracewell' 'Mohit Rathee' 'MW Short' 'YV Dhull'
 'Yudhvir Singh' 'Atharva Taide' 'Liton Das' 'PD Salt' 'Vijaykumar Vyshak'
 'Abdul Basith' 'Arjun Tendulkar' 'JP Behrendorff' 'AJ Hosein'
 'Naveen-ul-Haq' 'Noor Ahmad' 'KM Asif' 'JE Root' 'Sanvir Singh'
 'MD Shanaka' 'Vivrant Sharma' 'DG Nalkande' 'R Ravindra' 'SD Hope'
 'Sumit Kumar' 'Azmatullah Omarzai' 'SZ Mulani' 'G Coetzee' 'Naman Dhir'
 'SH Johnson' 'Sameer Rizvi' 'Akash Madhwal' 'SB Dubey' 'Mayank Dagar'
 'RJW Topley' 'A Raghuvanshi' 'Ashutosh Sharma' 'Nithish Kumar Reddy'
 'Saurav Chauhan' 'BR Sharath' 'Kumar Kushagra' 'WG Jacks'
 'J Fraser-McGurk' 'Tanush Kotian' 'KA Maharaj' 'Arshad Khan (2)'
 'R Sai Kishore' 'L Wood' 'LB Williams' 'AA Kulkarni' 'MJ Suthar'
 'RJ Gleeson' 'D Ferreira' 'Gulbadin Naib' 'A Kamboj' 'T Kohler-Cadmore'
 'Shivam Singh' 'V Viyaskanth' 'R Minz' 'RD Rickelton' 'PVSN Raju'
 'Aniket Verma' 'V Nigam' 'Priyansh Arya' 'J Overton' 'PWA Mulder'
 'PHKD Mendis' 'Suryansh Shedge' 'SK Rasheed' 'XC Bartlett' 'JP Inglis'
 'MS Bhandage' 'V Suryavanshi' 'A Mhatre' 'DS Rathi' 'Prince Yadav'
 'JG Bethell' 'C Bosch' 'KS Rathore' 'Urvil Patel' 'KT Maphaka' 'MJ Owen'
 'M Tiwari' 'L Ngidi' 'Sediqullah Atal' 'MP Breetzke' 'Musheer Khan'
 'BKG Mendis' 'DA Payne' 'S Arora' 'Harsh Dubey' 'FH Allen' 'MJ Henry'
 'Kartik Sharma' 'C Connolly' 'P Nissanka' 'MD Choudhary' 'Shivang Kumar'
 'PR Veer' 'Ashok Sharma' 'Auqib Nabi' 'GF Linde' 'LG Pretorius'
 'N Burger' 'PP Hinge' 'Himmat Singh' 'Brijesh Sharma' 'DV Malewar'
 'MP Yadav' 'Ashwani Kumar' 'Krish Bhagat' 'SU Parakh' 'N Sindhu'
 'R Smaran' 'E Malinga' 'Akshat Raghuwanshi']

Unique values in 'bowler':
['P Kumar' 'I Sharma' 'AB Agarkar' 'AB Dinda' 'JH Kallis' 'SC Ganguly'
 'LR Shukla' 'Z Khan' 'AA Noffke' 'SB Joshi' 'CL White' 'R Bhatia'
 'DL Vettori' 'MF Maharoof' 'B Geeves' 'JDP Oram' 'GD McGrath'
 'Joginder Sharma' 'SK Trivedi' 'SK Warne' 'YK Pathan' 'SR Watson'
 'D Salunkhe' 'MM Patel' 'M Muralitharan' 'JR Hopes' 'WA Mota' 'K Goel'
 'PP Chawla' 'B Lee' 'IK Pathan' 'S Sreesanth' 'P Amarnath' 'MS Gony'
 'DJ Hussey' 'Mohammad Hafeez' 'M Kartik' 'WPUJC Vaas' 'PP Ojha'
 'A Symonds' 'SB Bangar' 'DS Kulkarni' 'SB Styris' 'RP Singh'
 'Harbhajan Singh' 'B Akhil' 'R Vinay Kumar' 'A Nehra' 'AM Nayar'
 'ST Jayasuriya' 'SM Pollock' 'Pankaj Singh' 'VY Mahesh' 'Shahid Afridi'
 'Mohammad Asif' 'MA Khote' 'DJ Bravo' 'VS Yeligati' 'D Kalyankrishna'
 'VRV Singh' 'Sohail Tanvir' 'A Kumble' 'Yuvraj Singh' 'Shoaib Malik'
 'DNT Zoysa' 'SD Chitnis' 'JA Morkel' 'DW Steyn' 'CRD Fernando' 'V Sehwag'
 'V Kohli' 'Umar Gul' 'Gagandeep Singh' 'Y Venugopal Rao' 'M Ntini'
 'PJ Sangwan' 'DP Vijaykumar' 'SK Raina' 'S Vidyut' 'DJ Thornely'
 'RR Raje' 'L Balaji' 'CK Kapugedera' 'AD Mascarenhas' 'A Mishra'
 'Iqbal Abdulla' 'Shoaib Akhtar' 'PM Sarvesh Kumar' 'Abdur Razzak'
 'RR Powar' 'RA Jadeja' 'TM Dilshan' 'DR Smith' 'RG Sharma' 'A Nel'
 'DB Ravi Teja' 'LPC Silva' 'BAW Mendis' 'T Henderson' 'Kamran Khan'
 'SL Malinga' 'JD Ryder' 'A Flintoff' 'T Thushara' 'Harmeet Singh'
 'FH Edwards' 'MC Henriques' 'CH Gayle' 'VS Malik' 'DP Nannes' 'AM Salvi'
 'YA Abdulla' 'LRPL Taylor' 'KP Pietersen' 'RS Bopara' 'Anureet Singh'
 'MK Tiwary' 'RR Bose' 'KP Appanna' 'BJ Hodge' 'SR Tendulkar'
 'Shoaib Ahmed' 'JP Duminy' 'RE van der Merwe' 'S Tyagi' 'GR Napier'
 'SB Jakati' 'SM Harwood' 'AS Raut' 'D du Preez' 'RJ Harris' 'TL Suman'
 'A Singh' 'M Morkel' 'LA Carseldine' 'SS Sarkar' 'A Mithun' 'C Nanda'
 'AM Rahane' 'AD Mathews' 'J Botha' 'Mashrafe Mortaza' 'AB McDonald'
 'Y Nagar' 'R Ashwin' 'CK Langeveldt' 'Jaskaran Singh' 'RA Shaikh'
 'AA Jhunjhunwala' 'A Uniyal' 'SW Tait' 'R McLaren' 'R Sathish'
 'AG Murtaza' 'JM Kemp' 'RS Gavaskar' 'S Ladda' 'SE Bond' 'Bipul Sharma'
 'KA Pollard' 'S Narwal' 'SJ Srivastava' 'UT Yadav' 'AC Voges' 'J Theron'
 'R Sharma' 'NLTC Perera' 'KAJ Roach' 'PD Collingwood' 'C Ganapathy'
 'MB Parmar' 'DE Bollinger' 'SB Wagh' 'JD Unadkat' 'AP Dole' 'AN Ahmed'
 'FY Fazal' 'MR Marsh' 'L Ablish' 'S Sriram' 'AJ Finch' 'STR Binny'
 'ND Doshi' 'S Randiv' 'TG Southee' 'AUK Pathan' 'RV Gomez' 'AL Menaria'
 'DT Christian' 'M Manhas' 'WD Parnell' 'AC Thomas' 'NJ Rimmington'
 'JEC Franklin' 'RN ten Doeschate' 'S Nadeem' 'BA Bhatt' 'S Aravind'
 'R Ninan' 'JJ van der Wath' 'Shakib Al Hasan' 'PC Valthaty' 'S Dhawan'
 'J Syed Mohammad' 'VR Aaron' 'JE Taylor' 'NL McCullum' 'KMDN Kulasekara'
 'P Parameswaran' 'B Chipli' 'I Malhotra' 'B Kumar' 'AA Kazi'
 'Anand Rajan' 'P Prasanth' 'AA Chavan' 'Y Gnaneswara Rao' 'S Rana'
 'SS Mundhe' 'JP Faulkner' 'RW Price' 'M de Lange' 'GJ Maxwell'
 'KK Cooper' 'MN Samuels' 'TP Sudhindra' 'Ankit Sharma' 'DJ Harris'
 'F du Plessis' 'DAJ Bracewell' 'HV Patel' 'SP Narine' 'GB Hogg' 'P Awana'
 'RR Bhatkal' 'CJ McKay' 'V Pratap Singh' 'Azhar Mahmood' 'A Chandila'
 'LJ Wright' 'P Negi' 'RJ Peterson' 'A Ashish Reddy' 'R Shukla'
 'MJ Clarke' 'BW Hilfenhaus' 'SPD Smith' 'AD Russell' 'K Upadhyay'
 'Sunny Gupta' 'JJ Bumrah' 'MG Johnson' 'B Laughlin' 'AS Rajpoot'
 'S Badree' 'GH Vihari' 'Mohammed Shami' 'BMAJ Mendis' 'CH Morris'
 'S Kaul' 'R Rampaul' 'R Dhawan' 'MM Sharma' 'SMSM Senanayake' 'KV Sharma'
 'JO Holder' 'IC Pandey' 'YS Chahal' 'DJG Sammy' 'KW Richardson' 'P Suyal'
 'MG Neser' 'PV Tambe' 'BJ Rohrer' 'Parvez Rasool' 'Sandeep Sharma'
 'AC Gilchrist' 'NM Coulter-Nile' 'CJ Anderson' 'MA Starc' 'JDS Neesham'
 'AR Patel' 'M Vijay' 'R Tewatia' 'SA Yadav' 'Shivam Sharma' 'Imran Tahir'
 'V Shankar' 'LMP Simmons' 'BCJ Cutting' 'BE Hendricks' 'S Gopal'
 'K Santokie' 'PJ Cummins' 'JW Hastings' 'Karanveer Singh' 'DJ Muthuswami'
 'SA Abbott' 'KC Cariappa' 'TA Boult' 'J Suchith' 'DJ Hooda'
 'MJ McClenaghan' 'HH Pandya' 'D Wiese' 'RG More' 'SN Thakur' 'GS Sandhu'
 'J Yadav' 'Gurkeerat Singh' 'BB Sran' 'M Ashwin' 'CR Brathwaite'
 'C Munro' 'MP Stoinis' 'P Sahu' 'AF Milne' 'Mustafizur Rahman'
 'Kuldeep Yadav' 'KH Pandya' 'KJ Abbott' 'T Shamsi' 'S Kaushik'
 'SM Boland' 'Swapnil Singh' 'CJ Jordan' 'A Zampa' 'Sachin Baby' 'N Rana'
 'DL Chahar' 'KS Williamson' 'TS Mills' 'Rashid Khan' 'TM Head'
 'A Choudhary' 'BA Stokes' 'CR Woakes' 'B Stanlake' 'T Natarajan'
 'RD Chahar' 'Tejas Baroka' 'Basil Thampi' 'C de Grandhomme' 'AJ Tye'
 'LH Ferguson' 'Mohammad Nabi' 'Mohammed Siraj' 'Washington Sundar'
 'K Rabada' 'SS Agarwal' 'NB Singh' 'RA Tripathi' 'Ankit Soni' 'MJ Henry'
 'Avesh Khan' 'M Markande' 'MA Wood' 'K Khejroliya' 'Mujeeb Ur Rahman'
 'K Gowtham' 'DJM Short' 'TK Curran' 'Shivam Mavi' 'A Dananjaya'
 'JC Archer' 'LE Plunkett' 'IS Sodhi' 'MK Lomror' 'L Ngidi' 'KM Asif'
 'DJ Willey' 'M Prasidh Krishna' 'MM Ali' 'CJ Dala' 'S Lamichhane'
 'JPR Scantlebury-Searles' 'KK Ahmed' 'Navdeep Saini' 'S Dube'
 'Rasikh Salam' 'KMA Paul' 'SM Curran' 'CV Varun' 'GC Viljoen'
 'Mandeep Singh' 'MJ Santner' 'P Ray Barman' 'JP Behrendorff'
 'SC Kuggeleijn' 'AS Joseph' 'HF Gurney' 'S Midhun' 'R Parag' 'SN Khan'
 'LS Livingstone' 'Abhishek Sharma' 'Arshdeep Singh' 'SE Rutherford'
 'Harpreet Brar' 'Y Prithvi Raj' 'O Thomas' 'AS Roy' 'S Sandeep Warrier'
 'JL Pattinson' 'A Nortje' 'Ravi Bishnoi' 'SS Cottrell' 'JR Hazlewood'
 'KL Nagarkoti' 'I Udana' 'Abdul Samad' 'Kartik Tyagi' 'TU Deshpande'
 'CJ Green' 'Shahbaz Ahmed' 'DR Sams' 'Monu Kumar' 'DA Warner' 'P Dubey'
 'M Jansen' 'KA Jamieson' 'JA Richardson' 'RP Meredith' 'C Sakariya'
 'LI Meriwala' 'Lalit Yadav' 'Jalaj S Saxena' 'FA Allen' 'PWH de Silva'
 'AU Rashid' 'IC Porel' 'NT Ellis' 'VR Iyer' 'AK Markram' 'GHS Garton'
 'Akash Singh' 'GD Phillips' 'Umran Malik' 'K Yadav' 'RV Patel' 'OF Smith'
 'Akash Deep' 'Mohsin Khan' 'PVD Chameera' 'R Shepherd' 'Mukesh Choudhary'
 'D Pretorius' 'VG Arora' 'YBK Jaiswal' 'Tilak Varma' 'DG Nalkande'
 'M Theekshana' 'D Brevis' 'KR Sen' 'R Powell' 'Yash Dayal'
 'Aman Hakim Khan' 'Shashank Singh' 'OC McCoy' 'HR Shokeen' 'A Badoni'

In [ ]:
columns_to_check_nulls = ['player_of_match', 'batter', 'bowler', 'non_striker', 'wicket_kind', 'wicket_player_out']

for col in columns_to_check_nulls:
    print(f"\nNumber of null values in '{col}': {df[col].isnull().sum()}")

Number of null values in 'player_of_match': 828

Number of null values in 'batter': 0

Number of null values in 'bowler': 0

Number of null values in 'non_striker': 0

Number of null values in 'wicket_kind': 275267

Number of null values in 'wicket_player_out': 275267

In [ ]:
df['player_of_match']=df['player_of_match'].fillna("No Award", inplace=True)
df['wicket_kind'] = df['wicket_kind'].fillna('No Wicket')
df['wicket_player_out'] = df['wicket_player_out'].fillna('No Dismissal')

/tmp/ipykernel_1291/754778715.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['player_of_match']=df['player_of_match'].fillna("No Award", inplace=True)

3.9 Numerical Value Preprocessing

* No preprocessing required.
* Keep NaN values as is.

In [ ]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_cols:
    print(f"\nUnique values in numerical column '{col}':")
    print(df[col].unique())

Unique values in numerical column 'match_id':
[ 335982  335984  335983 ... 1529290 1529291 1529292]

Unique values in numerical column 'win_by_runs':
[140.  nan  33.   6.  66.  13.  10.  45.   9.   3.  29.   5.  18.  23.
  12.  65.  25.   1.  14.  41. 105.  75.  19.  92.  11.  24.  27.  38.
   8.  78.  16.  53.   2.   4.  31.  55.  98.  34.  36.  17.  39.  40.
  67.  63.  37.  57.  35.  22.  21.  48.  26.  20.  85.  32.  76. 111.
  82.  43.  58.  28.  74.  42.  59.  46.  47.   7.  86.  44.  87. 130.
  15.  60.  77.  30.  50.  93.  72.  62.  97. 138.  71. 144.  80.  51.
  61. 146.  64. 102. 118.  49.  69.  88.  54.  91.  52.  81.  56. 112.
 106. 100. 110.  83.  99. 103.]

Unique values in numerical column 'win_by_wickets':
[nan  9.  5.  6.  3.  7.  4. 10.  8.  2.  1.]

Unique values in numerical column 'innings':
[1 2 4 3 5 6]

Unique values in numerical column 'over':
[ 0  3  4  2  5  6 18 19  1  7 11 12 13 14 15  8  9 10 16 17]

Unique values in numerical column 'ball':
[ 1  2  3  4  5  6  7  8  9 10 11]

Unique values in numerical column 'runs_batter':
[0 2 1 6 4 5 3]

Unique values in numerical column 'runs_extras':
[1 0 4 2 5 3 7]

Unique values in numerical column 'runs_total':
[1 2 0 6 4 5 3 7]

Unique values in numerical column 'extras_wides':
[0 1 2 5 3 4]

Unique values in numerical column 'extras_noballs':
[0 1 2 5 3]

Unique values in numerical column 'extras_byes':
[0 4 1 2 3]

Unique values in numerical column 'extras_legbyes':
[1 0 4 2 3 5]

-----------------------------------------------OVER-------------------------------------------------------------